name: Check test vectors

on: pull_request

jobs:
  verify:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: ['rust', 'json', 'zcash']
        include:
          - kind: 'rust'
            name: 'Rust'
          - kind: 'json'
            name: 'JSON'
          - kind: 'zcash'
            name: 'Bitcoin-flavoured JSON'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Regenerate test vectors
        run: ./regenerate.sh ${{ matrix.kind }} all

      - name: Verify there are no changes
        run: git diff; git ls-files --others --exclude-standard; test -z "$(git status --porcelain)"
